# Generated by Django 3.2.9 on 2021-11-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sellingPrice',
        ),
    ]
