# Generated by Django 3.2.9 on 2021-11-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storemanagement', '0003_product_sellingprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=100)),
                ('invoiceDate', models.DateField()),
                ('customerName', models.CharField(max_length=100)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=100)),
                ('lineNumber', models.BigIntegerField()),
                ('productName', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storemanagement.product')),
                ('saleInvoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storemanagement.salesinvoice')),
            ],
        ),
    ]
